force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Zip</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SalesProcessTests.cls
/**
 * This class contains unit tests for validating the Sales process to
 * ensure no breaking changes in the Sales org.
 */
@isTest
private class SalesProcessTests {

    /**
    * Agents will enter properties with no price for opportunities with new home owner
    * where the house is not been appraised or put on the maarket yet.
    */
    @isTest
    static void createAndLinkPropertyWithNoPriceToOppurtunity() {
        Property__c property = new Property__c(Name='TestProperty', Address__c='123 Test Ave', City__c='Boston', Zip__c='12345');
        insert property;
        Opportunity opp = new Opportunity(Name='New House', StageName='Prospecting', CloseDate=system.today().addDays(3), Property__c=property.Id);
        insert opp;
        System.assert(opp.Property__c==property.Id);
    }
}